### ISSUE TITLE
Votetoban asks Mee6 block someone.

### ISSUE THREAD

**Issue by apple502j** [Kenny2github/kenny2automate#2]
Without any admins, votetoban asks mee6.
![Mee6, someone requests for Mee6 to be banned!](https://i.gyazo.com/dab84a9b7b591f8e86a5f31eef2c9e8b.png)

**Comment by Kenny2github** [comment]
Ayup, I'll try checking for bot

**Comment by apple502j** [comment]
Fixed.
![fixed](https://i.gyazo.com/0eed5c4116bf8027db5b81149962be21.png)
